Algoritmo "0 a 10"

Var
   Valor, salto, Contador: inteiro


Inicio
      Contador<-0
      Escreval("Quer contar até quanto ?")
      Leia(Valor)
      Escreval("Qual será o valor do salto ?")
      Leia(Salto)
      Enquanto (Contador<=Valor) faca
           Escreval(Contador)
           Contador <- Contador + Salto
           
      Fimenquanto
      Escreval("Terminei de contar ")

Fimalgoritmo